---
- hosts: all
  become: false
  gather_facts: true

  vars:
    distros:
      - Debian9
      - Debian10
      - RedHat7
      - RedHat8
      - Fedora30
      - Fedora31
      - Fedora32
      - Ubuntu16
      - Ubuntu18
      - Ubuntu20

  tasks:
    - name: Verify
      when: ansible_facts.distribution ~ ansible_facts.distribution_major_version in distros
      block:
        - name: Get fish version
          command: fish --version
          register: fish_version_check
          changed_when: false

        - name: Ensure proper fish version is installed
          ansible.builtin.assert:
            that:
              - fish_version is version('3', '==')
          vars:
            fish_version: "{{ fish_version_check.stdout.split(' ')[-1].split('.')[0] }}"
